name: d2batchest
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  add_2_calendar: ^3.0.1
  cached_network_image: ^3.3.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.15
  flutter:
    sdk: flutter
  flutter_timezone: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  rename_app: ^1.3.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
